Первый коммит тз9
SashaTyutyaev/java-filmorate pull request #5
Opened 2024-03-16 18:27 UTC by SashaTyutyaev

2024-03-18 11:03 UTC, TomattmanYandex requested changes
Привет

работа хорошая, критических моментов мало, но они есть 

еще из улучшений посмотри валидацию аннотациями, в реальных проектах она встречается чаще

2024-03-18 11:03 UTC, TomattmanYandex commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +    public void createFilm_With200CharDescription_ShouldReturnFilm() throws ValidationException {
тут коментарий который будет относиться ко всем тестовым методам а именно их именам
1) так как Should мы добавляем всегда, а When нет, то на второй позиции обычно пишется именно Should
2) если разделяешь нижними подчеркиваниями, то не обязательно уже писать слова Should и When
3) если пишешь Should то тогда пиши и When а то получается мешанина стилей
4) это уже совсем вкусовщина, но после разделения нижним подчеркивание можно начинать с маленькой буквы

2024-03-19 09:43 UTC, TomattmanYandex requested changes
Еще есть один момент

2024-03-19 09:43 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public User createUser(@RequestBody User user) {
я вижу что ты добавил аннотации на валдиацию в класс User но для того чтобы они работали надо тут в аргументах добавить аннотацию @Valid . Просто так она срабатывать не будет.
А когда ты ее добавишь и будешь валидировать через нее то текущий тест на валидацию работать не будет

А оставлять два способа делать одно и то же, когда один из них не работает это не логично

Рекомендую разобраться все же с валидацией аннотациями, и сделать так чтобы тут работала именно она и тесты с ней запустились, если не поймешь сам почему, пиши в чате, подскажу куда копатью

Если нету времени разбираться, то удаляй аннотации валидирования чтобы остался только один способ, но настоятельно рекомендую разобраться с ними, благодаря этому ты поймёшь как работает спринг, а это очень полезно

2024-03-19 09:54 UTC, SashaTyutyaev commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public User createUser(@RequestBody User user) {
Я их сначала добавил, потом решил убрать и вернуть как было, а тут видимо забыл) Попозже поправлю

2024-03-19 16:57 UTC, SashaTyutyaev commented
Аннотации удалил, а то время у меня уже поджимает, буду смотреть что нибудь по поводу них, чтобы понять

2024-03-20 17:13 UTC, TomattmanYandex approved these changes
Ну удалил аннотации и ладно
Там были бы проблемы с тестами потому что, чтобы применялись аннотации надо было достать контроллер из спрингового контекса а не создать конструктором

2024-03-21 16:49 UTC, merged