feat: добавлены service, storage, обработчик исключений
SashaTyutyaev/java-filmorate pull request #6
Opened 2024-03-31 18:16 UTC by SashaTyutyaev

2024-03-31 18:25 UTC, SashaTyutyaev commented
Тесты типо не прошел, рискну все таки отправить на проверку. В тз просят при ошибки валидации выбросить код 400, а в тестах постман он при ошибки валидации просит 500.

2024-04-01 13:33 UTC, TomattmanYandex requested changes
Привет, комменты в коде

2024-04-01 13:33 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    @Autowired
тут можно сделать так же как и в фильм контроллере

2024-04-01 13:33 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/FilmNotFoundException.java
> +public class FilmNotFoundException extends RuntimeException {
у тебя есть дв еошибки которые по сути отвечают за одно и то же, и обрабатываются одинаково,
почему бы не создать одну ошибку 
EntityNotFoundException и использовать ее вместо этих двух, а детали передавать в сообщении

2024-04-01 13:33 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private final Set<Integer> films = new LinkedHashSet<>();
почему выбран именно LInkedHashSet?

2024-04-01 13:33 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    InMemoryFilmStorage inMemoryFilmStorage;
1) модификаторы доступа
2) тут можно сделать так же как и порекомендовал в контроллере

2024-04-01 13:33 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    Comparator<Film> filmComparator = new Comparator<Film>() {
или стоит добавить модификатор доступа,
или сделать компаратор отдельным классом
или так как он используется только в одном месте, создать его на уровне метода

2024-04-01 13:33 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        User user = userService.getMapOfUsers().get(userId);
почему бы вместо того чтобы получать всю мапу пользователей, а потом искать в ней одного, не  получать сразу только одного по идентификатору?
подробнее про это наверное откоментируюсь в репозитории

2024-04-01 13:33 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        Film film = getMapOfFilms().get(filmId);
аналогично

2024-04-01 13:33 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (user.getFilms().size() > listFilmSize) {
сложно как то
if(!user.getFilms().contains(filmId)) {
//фильм не найден, добавляем его, увеличиваем количество лайков
}

2024-04-01 13:33 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public UserService(InMemoryUserStorage inMemoryUserStorage) {
Аналогично про конструктор

2024-04-01 13:33 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        User user = getMapOfUsers().get(userId);
аналогично про мапы

2024-04-01 13:33 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private final Set<Integer> films = new LinkedHashSet<>();
и второе
не очень понятное имя переменной, если не знать условие задания, тяжело понять что это про залайканные фильмы
почему бы не назвать likedFilms

2024-04-01 13:33 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Integer likes;
лучше бы назвать likesCount ибои в переменной с именем likes я бы хранил как раз таки список всех пользователей лайкнувших фильм

2024-04-01 13:33 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    InMemoryFilmStorage inMemoryFilmStorage;
3) тут у нас есть интерфейс, и мы будем использовать разные имплементации его, следовательно инжектить стоит по интерфейсу

например мы сейчас используешь методы, которые есть только в классе, и следовательно, если ты добавишь новую имплементацию в  следующем спринте, то чтобы тебе ее использовать прийдется не только ее заменить, но и ее использования

2024-04-01 13:33 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    private InMemoryUserStorage inMemoryUserStorage;
используем по интерфейсу

2024-04-01 13:33 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    private void validateFilm(Film film) throws ValidationException {
1) хранилища обычно не несут в себе никакой бизнес логики
2) валидация обьекта который приходит в контроллер, должна проходить на уровне контроллера
ну или на уровне сервиса, если нам для этого нужен доступ в базу
представь что у нас гораздо больше логики при создании фильма,
если мы провалидируем входящий объект на уровне контроллера, то мы сразу знаем, что объект валидный, и тогда продолжим его проверять, либо что объект неправильный, и тогда сразу возвращаем ошибку, без всяких дополнительных действий

а на уровне сервиса можно добавить валидацию, которая требует доступа в базу данных, например, что пользователь который ставит лайк, существует в базе данных

2024-04-01 13:33 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    public Map<Integer,Film> getMapOfFilms() {
1) так как мы должны использовать по интерфейсу, то лучше  чтобы публичными были только те методы которые есть в интерфейсе, чтобы когда мы будем заменять имплементацию, не было никаких проблем
2) обычно на уровне хранилища создаются базовые операции
CRUD create, read, update, delete а их комбинация для работы, это уже уровень сервиса
3) обычно хранилище имеет различные методы на получение данных
но обычно это получить один по идентифкатору, получить список или какую то аналогичную коллекцию по набору каких то параметров, получение мапы, со всеми значениями, это как то излишне
4) получение по идентификатору можно чтобы возвращало вместо null -  Optional а у него есть удобные методы, которые помогают обработать несуществующее значение

2024-04-01 13:33 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +public class InMemoryUserStorage implements UserStorage {
тут будут такие же комментарии как и в другом хранилище

2024-04-01 13:33 UTC, TomattmanYandex commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +    InMemoryUserStorage inMemoryUserStorage = new InMemoryUserStorage();
1) в спринговых тестах можно так же инжектить зависимости как и в основном приложении
возможно через другую аннотацию
2) тут снова вопрос про то где валидировать, - довольно таки странно, что для того чтобы протестировать контроллер, нужна вся цепочка (хотя получается нормальный интеграционный тест

2024-04-03 15:52 UTC, TomattmanYandex requested changes
Привет, добавил еще кучку комментариев

2024-04-03 15:52 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +package ru.yandex.practicum.filmorate.controller;
Кстати да, не существенно но глаза мозолит, может выкинуть немного в другой пакет, чтобы не мозолило глаза, ибо это ну ни как ни контроллер)

2024-04-03 15:52 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @Autowired
теперь когда у тебя сервисы помечены как private final 
есть возможность их заинжектить только через конструктор, и следовательно аннотация Autowirede избыточна

2024-04-03 15:52 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (filmService.getFilms().contains(filmService.getFilmById(id))) {
это уже бизнес логика она должна быть в сервисе

это обработать лучше следующим образом
1) валидируем поля обьекта (методом validateFilm а лучше аннотациями) 
2) вызываем метод filmService.addLike(id, userId);
а уже метод addLike внтри себя проверяет существует ли пользователь и существует ли фильм и добавляет лайк (а если не найден то кидает ошибку throw new EntityNotFoundException с сообщением, что не найдено, фильм или пользователь

2024-04-03 15:52 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (filmService.getFilms().contains(filmService.getFilmById(id)) && userService.getUsers().contains(userService.getUserById(userId))) {
аналогично как в коментарии выше











аналогично как и в комментарии выше

2024-04-03 15:52 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            validateFilm(filmService.getFilmById(id));
А зачем тут вообще валидировать фильм, ведь если он у нас в базе, то значит уже валидный

2024-04-03 15:52 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final UserService userService;
а зачем тут этот сервис, я так и не увидел где он используется

2024-04-03 15:52 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (userService.getUsers().contains(userService.getUserById(id)) && userService.getUsers().contains(userService.getUserById(friendsId))) {
логика сервиса

2024-04-03 15:52 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +@RequiredArgsConstructor
все комментарии из фильм контроллера относятся и к этому контроллеру

2024-04-03 15:52 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    @Autowired
Про аннотоации то же что и в контроллере

2024-04-03 15:52 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private final FilmStorage inMemoryFilmStorage;
я бы рекомендовал назвать переменную просто filmStorage в следующем спринте у вас появится новый тип хранилищ, и для того, чтобы все было логично, тип переменной трогать не придётся а вот название переменной надо будет

2024-04-03 15:52 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        return inMemoryFilmStorage.getFilmById(id);
в идеале, этот метод мог бы проверять вернулось null или нет и если null то создавать ошибку EntityNotFoundException 
и тогда, везде где ты будешь использовать этот метод, если обьект не найден, то будет пробрасываться эта ошибка, и не надо будет проверять много раз

2024-04-03 15:52 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (film == null) {
выше написал как это сделать лучше

2024-04-03 15:52 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public User getUserById(Integer id) {
тут так же как и с фильмом можно сделать

2024-04-03 15:52 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    public Film createFilm(@RequestBody Film film) {
тут аннотация @RequestBody не нужна, как и вообще на уровне хранилища, она только для контроллеров, чтобы он понимал, где брать обьект

2024-04-03 15:52 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +    public User createUser(@RequestBody User user) {
аналогично про аннотацию

2024-04-03 20:18 UTC, SashaTyutyaev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        return inMemoryFilmStorage.getFilmById(id);
Вопрос возник. Постман хотел код 404, но сначала выдавал 400, потому что в контроллере мы же сначала валидируем, а потом вызываем, например, addlike. Пока проверка на нулл была была в методе addlike, он выкидывал 400, но после переноса в метод getbyid, он стал выкидывать 404. Почему так? У нас же в контроллере порядок действий не изменился и так же осталась сначала валидация, а потом addlike

2024-04-04 17:25 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (getMapOfFilms().get(id) == null) {
у репозитория есть метод который возвращает фильм по идентификатору,
зачем тебе получать все фильмы, чтобы получить один?
представь что у тебя в хранилище 1_000_000 фильмов, каждый раз когда ты захочешь получить один, ты будешь получать все?

2024-04-04 21:23 UTC, TomattmanYandex requested changes
Осталось пара мелочей

2024-04-04 23:31 UTC, TomattmanYandex approved these changes

2024-04-20 13:40 UTC, merged